#!/usr/bin/env node
'use strict';

/**
 * Build step (zero dependencies):
 *   1. Read every data/part-*.json (each an array of recipes).
 *   2. Merge + sort by category, then id.
 *   3. Write recipes.json (the canonical, searchable index).
 *   4. Write one markdown file per recipe into recipes/.
 *   5. Write recipes/README.md (a browsable index table).
 *   6. Write site/recipes.js so the static site works from file:// with no server.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const RECIPES_DIR = path.join(ROOT, 'recipes');
const SITE_DIR = path.join(ROOT, 'site');

function readParts() {
  if (!fs.existsSync(DATA_DIR)) {
    console.error('data/ directory not found.');
    process.exit(1);
  }
  const parts = fs
    .readdirSync(DATA_DIR)
    .filter((f) => /^part-.*\.json$/.test(f))
    .sort();
  if (!parts.length) {
    console.error('No data/part-*.json files found.');
    process.exit(1);
  }
  const all = [];
  for (const file of parts) {
    const full = path.join(DATA_DIR, file);
    let arr;
    try {
      arr = JSON.parse(fs.readFileSync(full, 'utf8'));
    } catch (err) {
      console.error(`Could not parse ${file}: ${err.message}`);
      process.exit(1);
    }
    if (!Array.isArray(arr)) {
      console.error(`${file} must contain a JSON array.`);
      process.exit(1);
    }
    all.push(...arr);
  }
  return all;
}

function sortRecipes(recipes) {
  return recipes.slice().sort((a, b) => {
    if (a.category !== b.category) return a.category.localeCompare(b.category);
    return a.id.localeCompare(b.id);
  });
}

function recipeToMarkdown(r) {
  return `# ${r.title}

> ${r.use_case}

| | |
|---|---|
| **ID** | \`${r.id}\` |
| **Category** | \`${r.category}\` |
| **Best with** | ${r.agent} |

## Prompt

\`\`\`text
${r.prompt}
\`\`\`

## Safety notes

${r.safety_notes}

## Expected output

${r.expected_output}

---

_Part of [agent-recipes](../README.md) — free copy-paste recipes for AI coding agents._
`;
}

function buildIndexMarkdown(recipes) {
  const byCat = {};
  for (const r of recipes) {
    (byCat[r.category] = byCat[r.category] || []).push(r);
  }
  let md = `# Recipes index\n\n${recipes.length} recipes. Browse below, or use the CLI:\n\n\`\`\`bash\nnode bin/agent-recipes.js list\nnode bin/agent-recipes.js show <id>\n\`\`\`\n`;
  for (const cat of Object.keys(byCat).sort()) {
    md += `\n## ${cat}\n\n`;
    md += `| Recipe | ID | Best with |\n|---|---|---|\n`;
    for (const r of byCat[cat]) {
      md += `| [${r.title}](./${r.id}.md) | \`${r.id}\` | ${r.agent} |\n`;
    }
  }
  md += `\n---\n\n_Generated by \`scripts/build.js\`. Do not edit by hand._\n`;
  return md;
}

function main() {
  const recipes = sortRecipes(readParts());

  // 1. recipes.json
  fs.writeFileSync(
    path.join(ROOT, 'recipes.json'),
    JSON.stringify(recipes, null, 2) + '\n'
  );

  // 2. per-recipe markdown
  if (!fs.existsSync(RECIPES_DIR)) fs.mkdirSync(RECIPES_DIR, { recursive: true });
  for (const r of recipes) {
    fs.writeFileSync(
      path.join(RECIPES_DIR, `${r.id}.md`),
      recipeToMarkdown(r)
    );
  }

  // 3. recipes/README.md
  fs.writeFileSync(
    path.join(RECIPES_DIR, 'README.md'),
    buildIndexMarkdown(recipes)
  );

  // 4. site data as JS (works on file:// — no fetch/CORS needed)
  if (!fs.existsSync(SITE_DIR)) fs.mkdirSync(SITE_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(SITE_DIR, 'recipes.js'),
    `// Auto-generated by scripts/build.js — do not edit.\nwindow.RECIPES = ${JSON.stringify(
      recipes
    )};\n`
  );

  console.log(
    `Built ${recipes.length} recipes -> recipes.json, recipes/*.md, site/recipes.js`
  );
}

main();
